GET http://localhost:4004/odata/v4/library-srv/

###
GET http://localhost:4004/odata/v4/library-srv/BooksSet

###
GET http://localhost:4004/odata/v4/library-srv/BooksSet(11111111-1111-1111-1111-111111111111)

###
POST http://localhost:4004/odata/v4/library-srv/BooksSet
Content-Type: application/json

{
  "title": "Working Effectively with Legacy Code",
  "author": "Michael Feathers",
  "price": -49.99,
  "publishedDate": "2004-09-22T00:00:00Z",
  "digitalCopy": true
}

###
PUT http://localhost:4004/odata/v4/library-srv/BooksSet(11111111-1111-1111-1111-111111111111)
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "price": 51.99,
  "publishedDate": "2026-09-22T00:00:00Z",
  "digitalCopy": true
}

###
DELETE http://localhost:4004/odata/v4/library-srv/BooksSet(ace2386c-a6a6-4827-b64d-b5211496f528)